---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /user/bin/python3
      ansible_become_user: root
      ansible_become_password: YOUR_PASSWORD_HERE
      hostname: vtn-01
      update_cache: false
