---
- name: Setup OS environment
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ hostname }}"

    - name: Create vt_app group
      group:
        name: vt_app

    - name: Create vt_app user
      user:
        name: vt_app
        group: vt_app

    - name: Setup DNS server
      lineinfile:
        path: /etc/resolv.conf
        line: nameserver 8.8.8.8

    - name: Install utility tools
      package:
        name: "{{ item }}"
        state: present
        update_cache: "{{ update_cache }}"
      loop:
          - curl
          - wget
          - htop
  
    # - name: Install utility tools
    #   apt:
    #     name: "{{ item }}"
    #     state: present
    #     update_cache: "{{ update_cache }}"
    #   loop:
    #       - curl
    #       - wget
    #       - htop
    #   when: ansible_facts["distribution"] == "Ubuntu"
    
    # - name: Install utility tools
    #   yum:
    #     name: "{{ item }}"
    #     state: present
    #     update_cache: "{{ update_cache }}"
    #   loop:
    #       - curl
    #       - wget
    #       - htop
    #   when: ansible_facts["distribution"] == "CentOS"  

    - name: SSH hardening
      copy:
        src: ../templates/ssh_hardening.conf
        dest: /etc/ssh/sshd_config.d/ssh_hardening.conf
      notify: "Restart SSH"


  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
