---
- name: Setup OS environment
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Set hostname
      shell: 
        cmd: hostnamectl set-hostname vtn_01

    - name: Create vt_app group
      shell:
        cmd: groupadd vt_app
        # cmd: groupadd -f vt_app

    - name: Create vt_app user
      shell:
        cmd: useradd vt_app -g vt_app
        # cmd: "(groups vt_app | awk -F ' : ' '{print $2}' | grep vt_app) || useradd vt_app -g vt_app" 

    - name: Setup DNS server
      shell: 
        cmd: echo nameserver 8.8.8.8 >> /etc/resolv.conf
    
    - name: Update system packages
      shell:
        cmd: apt update

    - name: Install utility tools
      shell:
        cmd: apt install -y curl wget htop

    - name: Disable SSH root login
      shell:
        cmd: sed -i 's/^PermitRootLogin.*$/PermitRootLogin no/g' /etc/ssh/sshd_config

    - name: Restart SSH
      shell:
        cmd: systemctl restart sshd.service
